#!/usr/bin/env oo-ruby
# -*- ruby -*-

require 'rubygems'
require 'openshift-origin-common'
require 'openshift-origin-node'
require 'systemu'
require 'digest/md5'

config = OpenShift::Config.new

cart = "diy-0.1"
hook_dir = File.join(config.get("CARTRIDGE_BASE_PATH"), cart, "info/hooks")

(1000...20000).each do |idx|

  name = "foo#{idx}"
  namespace = "bar#{idx}"
  uid = idx
  uuid = Digest::MD5.hexdigest("#{name}-#{namespace}").to_s

  puts "Creating: #{idx}"

  next if File.exists?(File.join(config.get("GEAR_BASE_DIR"), uuid))

  begin
    container = OpenShift::ApplicationContainer.new(uuid, uuid, uid,
                                                    name, name, namespace)
    container.create

    hook = File.join(hook_dir, 'configure')
    cmd = "#{hook} #{name} #{namespace} #{uuid}"
    rc, out, err = systemu cmd
    if rc != 0
      raise Exception.new("#{cmd} = #{rc} #{out} #{err}")
    end

    hook = File.join(hook_dir, 'stop')
    cmd = "#{hook} #{name} #{namespace} #{uuid}"
    rc, out, err = systemu cmd
    if rc != 0
      raise Exception.new("#{cmd} = #{rc} #{out} #{err}")
    end
    
  rescue => e
    $stderr.write("Exception: #{e.inspect}\n")
  end

end
