#!/usr/bin/env oo-ruby
# -*- ruby -*-

require 'rubygems'
require 'openshift-origin-node'
require 'digest/md5'
require 'etc'


namespace="test"
cart_name="php-5.3"
ncreat=100

idx=0
Etc.passwd { |u| idx=[idx, u.uid+1].max }

cpids = []

stime = Time.now
ncreat.times.each do
  
  app_name="test#{idx}"

  digest = Digest::MD5.new
  digest.update("#{app_name}-#{namespace}")
  app_uuid=digest.to_s


  cpid = fork do
    container = OpenShift::ApplicationContainer.new(app_uuid, app_uuid, nil, app_name, app_name,
                                                    namespace, nil, nil, nil)
    container.create
    container.configure(cart_name)
    container.post_configure(cart_name)
    container.stop(cart_name)
  end
  cpids << cpid
  if cpids.length >= 5
    Process.waitpid2(cpids.slice!(0))
  end
  idx = idx +1
end

cpids.each do |cpid|
  Process.waitpid2(cpid)
end


elapsed = (Time.now - stime).to_f
puts "Time Elapsed (s): #{elapsed}"
