#!/usr/bin/env oo-ruby
# -*- ruby -*-

require 'rubygems'
require 'openshift-origin-node'

cart_name = "php-5.3"

cpids = []

apps=[]
OpenShift::ApplicationContainer.all.each do |container|
  apps << container
end

sp = [0, (apps.length/2)-50].max

puts "Restarting: #{apps[sp,100].length} of #{apps.length}"

stime = Time.now

apps[sp,100].each do |container|
  cpid = fork do
    container.start(cart_name)
    container.stop(cart_name)
  end
  cpids << cpid
  if cpids.length >= 5
    Process.waitpid2(cpids.slice!(0))
  end
end
cpids.each do |cpid|
  Process.waitpid2(cpid)
end

elapsed = (Time.now - stime).to_f
puts "Time Elapsed (s): #{elapsed}"
